version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-31-233-101.eu-west-1.compute.amazonaws.com
            database: d655ot8baaau1
            schema: public
            user: ujsxxivkrmifwl
            password: 90abc2818db9dc17dc0926d0974fd49e3f5571e2031405e8588460b53a0ac13e
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
